# golangci-lint configuration for CIPgram
# Note: Due to version compatibility issues, we primarily use Makefile-based linting
# This config serves as documentation of our intended linting rules

version: 2

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gofmt
    - govet
    - staticcheck