# Purdue Model Network Configuration
# This YAML file maps network subnets to Purdue Model levels and device roles
#
# Purdue Model Levels:
# - Level 1: Field devices (PLCs, RTUs, sensors, actuators, drives)
# - Level 2: Supervisory control (HMIs, SCADAs, historians)
# - Level 3: Manufacturing operations (MES, production scheduling)

mappings:
  # Level 1 - Field Device Networks
  - cidr: "192.168.1.0/24"
    level: "Level 1"
    role: "PLC Network"
  
  - cidr: "10.1.0.0/16"
    level: "Level 1" 
    role: "I/O Devices"
    
  - cidr: "172.16.100.0/24"
    level: "Level 1"
    role: "Safety Systems"
    
  # Level 2 - Supervisory Control Networks  
  - cidr: "192.168.10.0/24"
    level: "Level 2"
    role: "HMI Network"
    
  - cidr: "10.2.0.0/16"
    level: "Level 2"
    role: "SCADA Systems"
    
  - cidr: "172.16.200.0/24"
    level: "Level 2"
    role: "Historians"
    
  # Level 3 - Manufacturing Operations Networks
  - cidr: "192.168.20.0/24"
    level: "Level 3"
    role: "MES Network"
    
  - cidr: "10.3.0.0/16"
    level: "Level 3"
    role: "Production Management"
    
  - cidr: "172.16.30.0/24"
    level: "Level 3"
    role: "ERP Integration"

  # Common industrial device subnets
  - cidr: "192.168.100.0/24"
    level: "Level 1"
    role: "Rockwell/Allen-Bradley"
    
  - cidr: "192.168.101.0/24"
    level: "Level 1"
    role: "Siemens S7"
    
  - cidr: "192.168.102.0/24"
    level: "Level 1"
    role: "Schneider Modicon"
    
  - cidr: "192.168.103.0/24"
    level: "Level 1"
    role: "GE Fanuc"
    
  - cidr: "192.168.104.0/24"
    level: "Level 1"
    role: "Omron"
    
  - cidr: "192.168.105.0/24"
    level: "Level 1"
    role: "Mitsubishi"

  # Multicast ranges commonly used in industrial networks
  - cidr: "224.0.2.0/24"
    level: "Level 1"
    role: "EtherNet/IP Multicast"
    
  - cidr: "239.192.1.0/24"
    level: "Level 1"
    role: "Profinet Multicast"
